### ISSUE TITLE
Newer releases of SpringCloud support

### ISSUE THREAD

**Issue by popand** [VanRoy/spring-cloud-dashboard#10]
First awesome tool and thanks for providing it.  Was wondering if you are looking to maintain it moving forward with the newer releases of spring cloud as the newer ones are breaking majority of the dashboard functionality.

Thanks

**Comment by VanRoy** [comment]
@popand , Indeed I working on moving to newer Spring Cloud.
Can you send me more details on functionality that don't work with the newer version of Spring Cloud ?

Thanks.

**Comment by popand** [comment]
That is awesome.. thanks for offering to maintain this moving forward.

The issue that I've seen is black page when services are registered and running.

This is with any version of Brixton M1 or later.

<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-parent</artifactId>
                <version>Brixton.M1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>


Although for M1 we were able to get it work by updating the LocaleEurekaRepository to use the PeerAwareInstanceRegistryImpl instead of the PeerAwareInstanceRegistry class.

With updating to Brixton M2 or later things break again.

![image](https://cloud.githubusercontent.com/assets/637144/12247833/c5e093a2-b883-11e5-8dab-4fd2fb698c95.png)

**Comment by VanRoy** [comment]
Hi @popand,
I have just finished Brixton migration of SpringCoudDashboard.
Can you try the last version and give me your feedback ?

**Comment by daniellavoie** [comment]
I've been testing your Brixton branch for a while. No problem to report. We are going for production in 2 weeks.

**Comment by popand** [comment]
Yes of course .. will have a look and let you know if any issues.

Thanks,
Andrei

**Comment by VanRoy** [comment]
@popand , @daniellavoie  I just released the 1.1.0.RELEASE version including support of Brixton and Spring Boot 1.3.5.

Please feel free to share with me if you notice any problems.

Thanks.
Julien.
