### ISSUE TITLE
Unable to package and use

### ISSUE THREAD

**Issue by lduparc** [VanRoy/spring-cloud-dashboard#11]
Hi,

I have clone your project in order to merge your version and the spring-boot-admin project. I want update the UI.

Before merge I have tried to package and use your project as a dependency in another spring boot app but I have the following error during compilation:

`
/Users/xxxx/Projects/microservices/support/microservice-admin/src/main/java/applications/microservices/support/AdminApplication.java:8: error: package com.github.vanroy.cloud.dashboard.config does not exist
import com.github.vanroy.cloud.dashboard.config.EnableCloudDashboard;
                                               ^
/Users/xxxx/Projects/microservices/support/microservice-admin/src/main/java/applications/microservices/support/AdminApplication.java:15: error: cannot find symbol
@EnableCloudDashboard
 ^
  symbol: class EnableCloudDashboard
2 errors
:compileJava FAILED
`  

Morever, If I use your version on maven repository and the details view is broken and on the dashboard every "Health" is marked as DOWN but I go to the http://localhost:8765/health I can see all health information.

Have any idea about the issues.. ?

**Comment by VanRoy** [comment]
Hi @lduparc ,

Thanks for you feedback.
You can find a work in progress about spring-boot-admin recent merge on this branch : https://github.com/VanRoy/spring-cloud-dashboard/tree/feature/beanstalk

Please, tell me if it's working for you.

I will release it that after the Spring Cloud 1.1.0 release.

Thanks.
Julien.

**Comment by VanRoy** [comment]
@lduparc ,

I have just finished Brixton migration of SpringCoudDashboard.
I retrieved the last SpringBootAdmin feature too.

Can you try the last version and give me your feedback ?

**Comment by lduparc** [comment]
@VanRoy 

I will try it on the next week and keep you up to date.

**Comment by VanRoy** [comment]
@lduparc I just released the 1.1.0.RELEASE version including support of Brixton and Spring Boot 1.3.5.

Can you try this new version and tell me if it's solve your problem ?

Thanks.
Julien.

**Comment by lduparc** [comment]
Sorry for the delay, everything works fine !! Thank you.
