### ISSUE TITLE
Is it possible to customize the UI?

### ISSUE THREAD

**Issue by varghgeorge** [VanRoy/spring-cloud-dashboard#12]
Thanks, this is great.. and what I was looking for!!
Looking forward to using it with latest spring boot. 

Meanwhile, is it possible to customize (basic - adding logo, name etc.) the dashboard?

**Comment by VanRoy** [comment]
@varghgeorge , 

You can find a preview of Spring Boot migration on this branch : https://github.com/VanRoy/spring-cloud-dashboard/tree/feature/brixton

It will be coming after Spring Cloud 1.1.0 release.

For the customisation, it's not acutally possible. Feel free to send me a PR if you can.

**Comment by daniellavoie** [comment]
Hi @VanRoy 

Nice work on the Dashboard ! I'm also interrested in a customized UI. I'll try to send a PR this weekend or the next one.

**Comment by daniellavoie** [comment]
Hi there, I've came to a conclusion a while ago on this subject, In fact I realized that it is possible to overload the HTML ressource by forking them directly in your server project which import the spring-cloud-dashboard dependencies. Which mean you can replace the original CSS or even fork the HTML pages and js files. @varghgeorge that should answer your need. Do you need an exemple or are you fine with that ? In my opinion, this issue can be closed.

**Comment by VanRoy** [comment]
@varghgeorge I just released the 1.1.0.RELEASE version including support of Brixton and Spring Boot 1.3.5.

The issue related to UI customization is been always an issue for you or can i close them ?

Thanks.
Julien.

**Comment by lduparc** [comment]
Customize the UI works on localhost but not after deploiement on my server.

I have copy all webapp resources into my dashboard resources.

**Comment by daniellavoie** [comment]
Provide an example project and I might be able to help you. I managed to build a package with a customized UI.

**Comment by lduparc** [comment]
See my project architecture below. Have you an example on github to find how to implement a custom UI ?

<img width="404" alt="capture d ecran 2016-08-21 a 2 41 31 pm" src="https://cloud.githubusercontent.com/assets/790935/17837242/a3e9cdb6-67ad-11e6-9cb8-51998a4e1b91.png">

**Comment by daniellavoie** [comment]
Upload your  project to github and I'll try to package it and see what's wrong.

**Comment by lduparc** [comment]
I can't share my project. But it's easy to test. Use a spring boot sample and add your webapp resources. It's working locally, but if you push your app on a remote server, the UI stay the default UI. All overriding does not appear.

**Comment by daniellavoie** [comment]
I am asking you to share a project because I personally deployed an UI customization to production. There must be something your are missing. The screenshot you sent is not enough.

**Comment by lduparc** [comment]
I have created a sample [here](https://github.com/lduparc/SBD).
I have modified the `overview.html` with a lot of `TEST` sequence.

This override works locally but not if I deploy the app on a my remote server.

Hope you will have everything.

**Comment by daniellavoie** [comment]
I packaged your app using gradle and ran it with a `java -jar eureka.jar` without problem. I was able to see you `overview.html` with the `TEST` madness. You sure it not a browser cache issue ?

**Comment by lduparc** [comment]
No, I have clean my cache. If I run `java -jar eureka.jar` on my computer it's working. But in my process I upload the jar to a nexus repository and start the app into a docker engine using a command like this: `java -Xms${XMS} -Xmx${XMX} -jar -Dspring.profiles.active=${PRO} /jars/${APP}-${VER}.jar`

And after deploy on my docker engine, I'm not able to see the UI overrided.

**Comment by lduparc** [comment]
If I unzip the jar builded locally, the folder WEB-INF contains the `/classes/public/views/... all html files`, but if I unzip the jar after upload to nexus repository, the WEB-INF folder does not contain `views`

**Comment by lduparc** [comment]
I found the issue. It was from my side. I change a setting on my nexus repository in order to include public resources. My default configuration excluded all public resources.

Sorry for false positive issue. You can close this issue.

**Comment by VanRoy** [comment]
@lduparc I'm Happy to see it's works fine now.
@daniellavoie Thanks a lot for your help.

**Comment by daniellavoie** [comment]
I'll try to come up with a doc update explaining how the UI can be customized.
