### ISSUE TITLE
Turbine URL

### ISSUE THREAD

**Issue by pakizito** [VanRoy/spring-cloud-dashboard#14]
Hi,
How can I configure the full URL to a certain service cluster?
I have a service running in https, but he always connects via http, is this configurable?
2016-03-20 16:44:58.625 ERROR 12748 --- [nio-1112-exec-7] c.g.v.c.d.s.CircuitBreakerStreamServlet  : Error proxying request: http://localhost:1112/turbine.stream?cluster=MYSERVICE
Thank you very much.

With kind regards,
Rodrigo

**Comment by VanRoy** [comment]
Hi @pakizito ,

Turbine URL can be customized by this property in your configuration (yaml or properties) : spring.cloud.dashboard.turbine.url

**Comment by VanRoy** [comment]
@pakizito , Did you have a little time to test my suggestion ?

Can i close this issue ?

**Comment by pakizito** [comment]
Yes, it worked like expected :) thanks
