### ISSUE TITLE
Support for basic Authentication header for secured actuator endpoints

### ISSUE THREAD

**Issue by daniellavoie** [VanRoy/spring-cloud-dashboard#16]
Sometimes, the actuator endpoints of the instances we are monitoring are secured.

The HttpClient instanciation in CloudDashboardConfig. could be customized to fit in a Basic Authentication Header if required by configuration.

I will work on a PR for this feature.

Edit : I made it work. I externalized all the HTTP configuration to a ConfigurationProperties.

Daniel

**Comment by VanRoy** [comment]
Hi @daniellavoie,

Thanks for your feedback.

Do you think it could be interesting to integrate your work on master branch via PR ?
Or may be can you send me a snippet of your code, I could be add it on samples or documentation.

Julien.

**Comment by daniellavoie** [comment]
@VanRoy On it ! Can' get the corporate code outside so I'm currently rewriting it at home (how stupid...). PR is incoming.

Daniel

**Comment by daniellavoie** [comment]
PR done. Let me know what you think about it. I would have like to place an integration test, but the current suite doesn't have an infrastructure to test a secured instance.

**Comment by VanRoy** [comment]
@daniellavoie Thanks, it's merged

**Comment by daniellavoie** [comment]
NP. Expect some other PR in the future as we will use your dashboard in production.

Thanks for tool !
