### ISSUE TITLE
Looks like documentation (README) is not in sync with release version 1.0.0

### ISSUE THREAD

**Issue by somas** [VanRoy/spring-cloud-dashboard#18]
Great tool. Thanks for creating it and thanks to the contributors.

Document has reference to 1.0.0 RELEASE for maven and it has reference to http client username/password ability but that is not available in 1.0.0 RELEASE.

Do you know when the next release is coming?

**Comment by VanRoy** [comment]
Hi @somas ,

Indeed the documentation if a little bit in advance.
The next release is the 1.1.0 ( including User/password, AWS Beanstalk support, Dashboard upgrade from Spring Boot Admin ) is planned for the next week.

Julien.

**Comment by somas** [comment]
Thanks @VanRoy, looking forward to the release
