### ISSUE TITLE
update the dependence

### ISSUE THREAD

**Issue by zhaopangithub** [VanRoy/spring-cloud-dashboard#23]
Can you update the dependence to the latest?thank you!

**Comment by VanRoy** [comment]
Hi @zhaopangithub, I will try to find a little bit of time to work on it.

Do you have any requirement ou issue to specific version ?

**Comment by zhaopangithub** [comment]
My project's spring boot version is 1.5. *, this dashbord spring boot version is  1.3. *, then happen the following error:**Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.ServletRegistrationBean**
But my project's spring boot version change to 1.3.5，then Everything is all right.
So I think that should be updated the  springboot version that dashbord dependented.

**Comment by VanRoy** [comment]
Hi @zhaopangithub ,

I have prepared the next 1.2.0-SNAPSHOT upgraded to Spring Boot 1.5 here : https://github.com/VanRoy/spring-cloud-dashboard/tree/1.2.x

Can you try this version and give me feedback ?
If it work as you expect, I can release it quickly.

Thanks.
Julien.

**Comment by winnerku** [comment]
I get another error with 1.2.0-SNAPSHOT 
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cache/aspectj/AspectJCachingConfiguration.class] cannot be opened because it does not exist

**Comment by VanRoy** [comment]
Hi @winnerku,

It's weird, dependency spring-aspects is already in the pom of spring-cloud-dashboard.
Can you send me a sample project for help me to reproduce your issue ?

Thanks.
Julien.

**Comment by REME-AlarmTILT** [comment]
Hello @VanRoy,
can you confirm that the dependency exists 
```
<dependency>
	<groupId>com.github.vanroy</groupId>
	<artifactId>spring-cloud-dashboard</artifactId>
	<version>1.2.0.RELEASE</version>
</dependency>
```
Thank you

**Comment by VanRoy** [comment]
Hi @REME-AlarmTILT , I just did it this morning.
1.2.0.RELASE is now available on maven central.
Thanks for your patience.

**Comment by Joy-Panda** [comment]
I'm sorry, I'm so busy lately that I don‘t ’have time to reply you. Just now, I've tried, and it can work well.
Thanks!
