### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by mmaryo** [VanRoy/spring-cloud-dashboard#24]
Hello

It seems that not works with java 9

        /opt/jdk-9.0.4/bin/java --illegal-access=warn -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=40639 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:/opt/idea-IU-173.3727.127/lib/idea_rt.jar=41069:/opt/idea-IU-173.3727.127/bin -Dfile.encoding=UTF-8 -classpath /home/me/dev/mmh/vishnou/odin/target/classes:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-starter-eureka-server/1.2.5.RELEASE/spring-cloud-starter-eureka-server-1.2.5.RELEASE.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-starter/1.1.7.RELEASE/spring-cloud-starter-1.1.7.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter/1.4.4.RELEASE/spring-boot-starter-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot/1.4.4.RELEASE/spring-boot-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.4.4.RELEASE/spring-boot-autoconfigure-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.4.4.RELEASE/spring-boot-starter-logging-1.4.4.RELEASE.jar:/home/me/.m2/repository/ch/qos/logback/logback-classic/1.1.9/logback-classic-1.1.9.jar:/home/me/.m2/repository/ch/qos/logback/logback-core/1.1.9/logback-core-1.1.9.jar:/home/me/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.22/jcl-over-slf4j-1.7.22.jar:/home/me/.m2/repository/org/slf4j/jul-to-slf4j/1.7.22/jul-to-slf4j-1.7.22.jar:/home/me/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.22/log4j-over-slf4j-1.7.22.jar:/home/me/.m2/repository/org/springframework/spring-core/4.3.6.RELEASE/spring-core-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-context/1.1.7.RELEASE/spring-cloud-context-1.1.7.RELEASE.jar:/home/me/.m2/repository/org/springframework/security/spring-security-crypto/4.1.4.RELEASE/spring-security-crypto-4.1.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-commons/1.1.7.RELEASE/spring-cloud-commons-1.1.7.RELEASE.jar:/home/me/.m2/repository/org/springframework/security/spring-security-rsa/1.0.3.RELEASE/spring-security-rsa-1.0.3.RELEASE.jar:/home/me/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.55/bcpkix-jdk15on-1.55.jar:/home/me/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.55/bcprov-jdk15on-1.55.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-netflix-eureka-server/1.2.5.RELEASE/spring-cloud-netflix-eureka-server-1.2.5.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/1.4.4.RELEASE/spring-boot-starter-actuator-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-actuator/1.4.4.RELEASE/spring-boot-actuator-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-freemarker/1.4.4.RELEASE/spring-boot-starter-freemarker-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/freemarker/freemarker/2.3.25-incubating/freemarker-2.3.25-incubating.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-netflix-core/1.2.5.RELEASE/spring-cloud-netflix-core-1.2.5.RELEASE.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-netflix-eureka-client/1.2.5.RELEASE/spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar:/home/me/.m2/repository/com/netflix/eureka/eureka-client/1.4.12/eureka-client-1.4.12.jar:/home/me/.m2/repository/org/codehaus/jettison/jettison/1.3.7/jettison-1.3.7.jar:/home/me/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/home/me/.m2/repository/com/netflix/netflix-commons/netflix-eventbus/0.3.0/netflix-eventbus-0.3.0.jar:/home/me/.m2/repository/com/netflix/netflix-commons/netflix-infix/0.3.0/netflix-infix-0.3.0.jar:/home/me/.m2/repository/commons-jxpath/commons-jxpath/1.3/commons-jxpath-1.3.jar:/home/me/.m2/repository/joda-time/joda-time/2.9.7/joda-time-2.9.7.jar:/home/me/.m2/repository/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar:/home/me/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar:/home/me/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/home/me/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar:/home/me/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar:/home/me/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar:/home/me/.m2/repository/com/netflix/servo/servo-core/0.10.1/servo-core-0.10.1.jar:/home/me/.m2/repository/com/netflix/servo/servo-internal/0.10.1/servo-internal-0.10.1.jar:/home/me/.m2/repository/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar:/home/me/.m2/repository/com/sun/jersey/jersey-client/1.19.1/jersey-client-1.19.1.jar:/home/me/.m2/repository/com/sun/jersey/contribs/jersey-apache-client4/1.19.1/jersey-apache-client4-1.19.1.jar:/home/me/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar:/home/me/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/me/.m2/repository/com/netflix/governator/governator-api/1.12.10/governator-api-1.12.10.jar:/home/me/.m2/repository/com/sun/jersey/jersey-servlet/1.19.1/jersey-servlet-1.19.1.jar:/home/me/.m2/repository/com/sun/jersey/jersey-server/1.19.1/jersey-server-1.19.1.jar:/home/me/.m2/repository/com/netflix/eureka/eureka-core/1.4.12/eureka-core-1.4.12.jar:/home/me/.m2/repository/com/netflix/governator/governator/1.12.10/governator-1.12.10.jar:/home/me/.m2/repository/com/netflix/governator/governator-core/1.12.10/governator-core-1.12.10.jar:/home/me/.m2/repository/com/google/inject/extensions/guice-multibindings/4.0/guice-multibindings-4.0.jar:/home/me/.m2/repository/com/google/inject/extensions/guice-grapher/4.0/guice-grapher-4.0.jar:/home/me/.m2/repository/com/google/inject/extensions/guice-assistedinject/4.0/guice-assistedinject-4.0.jar:/home/me/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/home/me/.m2/repository/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar:/home/me/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar:/home/me/.m2/repository/com/netflix/archaius/archaius-core/0.7.4/archaius-core-0.7.4.jar:/home/me/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:/home/me/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/me/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.8.6/jackson-dataformat-xml-2.8.6.jar:/home/me/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.6/jackson-module-jaxb-annotations-2.8.6.jar:/home/me/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/home/me/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar:/home/me/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar:/home/me/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/home/me/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-starter-archaius/1.2.5.RELEASE/spring-cloud-starter-archaius-1.2.5.RELEASE.jar:/home/me/.m2/repository/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.jar:/home/me/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/me/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.6/jackson-annotations-2.8.6.jar:/home/me/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.6/jackson-core-2.8.6.jar:/home/me/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.6/jackson-databind-2.8.6.jar:/home/me/.m2/repository/org/springframework/cloud/spring-cloud-starter-ribbon/1.2.5.RELEASE/spring-cloud-starter-ribbon-1.2.5.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-aop/1.4.4.RELEASE/spring-boot-starter-aop-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/spring-aop/4.3.6.RELEASE/spring-aop-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/retry/spring-retry/1.1.5.RELEASE/spring-retry-1.1.5.RELEASE.jar:/home/me/.m2/repository/com/netflix/ribbon/ribbon/2.2.0/ribbon-2.2.0.jar:/home/me/.m2/repository/com/netflix/ribbon/ribbon-transport/2.2.0/ribbon-transport-2.2.0.jar:/home/me/.m2/repository/io/reactivex/rxnetty-contexts/0.4.9/rxnetty-contexts-0.4.9.jar:/home/me/.m2/repository/io/reactivex/rxnetty-servo/0.4.9/rxnetty-servo-0.4.9.jar:/home/me/.m2/repository/com/netflix/hystrix/hystrix-core/1.5.6/hystrix-core-1.5.6.jar:/home/me/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar:/home/me/.m2/repository/io/reactivex/rxnetty/0.4.9/rxnetty-0.4.9.jar:/home/me/.m2/repository/io/netty/netty-codec-http/4.0.27.Final/netty-codec-http-4.0.27.Final.jar:/home/me/.m2/repository/io/netty/netty-codec/4.0.27.Final/netty-codec-4.0.27.Final.jar:/home/me/.m2/repository/io/netty/netty-handler/4.0.27.Final/netty-handler-4.0.27.Final.jar:/home/me/.m2/repository/io/netty/netty-transport-native-epoll/4.0.27.Final/netty-transport-native-epoll-4.0.27.Final.jar:/home/me/.m2/repository/io/netty/netty-common/4.0.27.Final/netty-common-4.0.27.Final.jar:/home/me/.m2/repository/io/netty/netty-buffer/4.0.27.Final/netty-buffer-4.0.27.Final.jar:/home/me/.m2/repository/io/netty/netty-transport/4.0.27.Final/netty-transport-4.0.27.Final.jar:/home/me/.m2/repository/com/netflix/ribbon/ribbon-core/2.2.0/ribbon-core-2.2.0.jar:/home/me/.m2/repository/com/netflix/ribbon/ribbon-httpclient/2.2.0/ribbon-httpclient-2.2.0.jar:/home/me/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/me/.m2/repository/com/netflix/netflix-commons/netflix-commons-util/0.1.1/netflix-commons-util-0.1.1.jar:/home/me/.m2/repository/com/netflix/ribbon/ribbon-loadbalancer/2.2.0/ribbon-loadbalancer-2.2.0.jar:/home/me/.m2/repository/com/netflix/netflix-commons/netflix-statistics/0.1.1/netflix-statistics-0.1.1.jar:/home/me/.m2/repository/io/reactivex/rxjava/1.1.10/rxjava-1.1.10.jar:/home/me/.m2/repository/com/netflix/ribbon/ribbon-eureka/2.2.0/ribbon-eureka-2.2.0.jar:/home/me/.m2/repository/org/slf4j/slf4j-api/1.7.22/slf4j-api-1.7.22.jar:/home/me/.m2/repository/com/github/vanroy/spring-cloud-dashboard/1.2.0.RELEASE/spring-cloud-dashboard-1.2.0.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.4.4.RELEASE/spring-boot-starter-web-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/1.4.4.RELEASE/spring-boot-starter-tomcat-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar:/home/me/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.11/tomcat-embed-el-8.5.11.jar:/home/me/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.11/tomcat-embed-websocket-8.5.11.jar:/home/me/.m2/repository/org/hibernate/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final.jar:/home/me/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/me/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar:/home/me/.m2/repository/com/fasterxml/classmate/1.3.3/classmate-1.3.3.jar:/home/me/.m2/repository/org/springframework/spring-web/4.3.6.RELEASE/spring-web-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/spring-beans/4.3.6.RELEASE/spring-beans-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/spring-webmvc/4.3.6.RELEASE/spring-webmvc-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/spring-expression/4.3.6.RELEASE/spring-expression-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-cache/1.4.4.RELEASE/spring-boot-starter-cache-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/springframework/spring-context/4.3.6.RELEASE/spring-context-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/spring-context-support/4.3.6.RELEASE/spring-context-support-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/springframework/boot/spring-boot-starter-thymeleaf/1.4.4.RELEASE/spring-boot-starter-thymeleaf-1.4.4.RELEASE.jar:/home/me/.m2/repository/org/thymeleaf/thymeleaf-spring4/2.1.5.RELEASE/thymeleaf-spring4-2.1.5.RELEASE.jar:/home/me/.m2/repository/org/thymeleaf/thymeleaf/2.1.5.RELEASE/thymeleaf-2.1.5.RELEASE.jar:/home/me/.m2/repository/ognl/ognl/3.0.8/ognl-3.0.8.jar:/home/me/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:/home/me/.m2/repository/org/unbescape/unbescape/1.1.0.RELEASE/unbescape-1.1.0.RELEASE.jar:/home/me/.m2/repository/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/1.4.0/thymeleaf-layout-dialect-1.4.0.jar:/home/me/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar:/home/me/.m2/repository/org/springframework/spring-aspects/4.3.6.RELEASE/spring-aspects-4.3.6.RELEASE.jar:/home/me/.m2/repository/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar:/home/me/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/home/me/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/home/me/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/me/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar fr.org.app.Application
        WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/home/me/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar) to method java.lang.Object.finalize()
        WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/home/me/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar) to method java.lang.Object.clone()
        WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/home/me/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar) to method java.lang.Object.registerNatives()
        WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/me/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
        2018-02-14 23:06:10.515  INFO 12320 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@77a98a6a: startup date [Wed Feb 14 23:06:10 CET 2018]; root of context hierarchy
        WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/me/.m2/repository/org/springframework/spring-core/4.3.6.RELEASE/spring-core-4.3.6.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
        2018-02-14 23:06:10.782  INFO 12320 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
        2018-02-14 23:06:10.847  INFO 12320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$82bf3d03] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
        2018-02-14 23:06:11.136 ERROR 12320 --- [           main] o.s.boot.SpringApplication               : Application startup failed

        org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
        found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
         in 'reader', line 22, column 1:
            		connectTimeout: 1000
            ^

        	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[snakeyaml-1.17.jar:na]

**Comment by VanRoy** [comment]
Hi @mmaryo, indeed I never test with J9.

Can you share with me a sample project, and I will try to find the issues with Java 9 ?

**Comment by mmaryo** [comment]
Just a new java project with that  : 


     @SpringBootApplication
     @EnableEurekaServer
     @EnableDiscoveryClient
     @EnableCloudDashboard
     public class Application {
	     public static void main(String[] args) {
		     SpringApplication.run(Application.class, args);
     	}
     }

**Comment by VanRoy** [comment]
Hi @mmaryo , Your stacktrace seems to be related to syntax error on application.yaml.

Do you have always your issue ?

**Comment by VanRoy** [comment]
@mmaryo ,

After few tests, I had successfully start the dashboard.

Two options : 

- Add JVM flags : 

--add-modules=java.xml.bind,java.activation

- Add dependencies in your pom.xml :

		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>

**Comment by mmaryo** [comment]
Thanks VanRoy I'll be use it!
