### ISSUE TITLE
Application version not showing on summary page

### ISSUE THREAD

**Issue by bobjana** [VanRoy/spring-cloud-dashboard#25]
Which property needs to be set in order to display version for eureka client application?
Also tried baking it into the jar manifest file which spring boot banner uses, but still blank (https://stackoverflow.com/questions/34519759/application-version-does-not-show-up-in-spring-boot-banner-txt)

**Comment by VanRoy** [comment]
Hi @bobjana , can you tell me where do you want to display the eureka client version ?

**Comment by bobjana** [comment]
Hi, thanks for the quick response. I'm reffering to the version column on
dashboard screenshot:
https://github.com/VanRoy/spring-cloud-dashboard#screenshot

**Comment by VanRoy** [comment]
It's extract from actuator /info endpoint in the service.

You can populate the version number in your application.yml 

```
info:
  name: My Application
  version: 1.0.0
```

If you build with maven you can use ResourceFiltering configured on spring-boot-starter-parent like this : 

```
info:
  version: @application.version@
```

**Comment by bobjana** [comment]
Thank you, that worked for me. Perhaps I misread the docs or above
information is not part of readme, adding it will make life easier for the
next person.

Regards,
Dylan

**Comment by VanRoy** [comment]
@bobjana Indeed it's a good enhancement. I keep it in my todo.
Thanks.
Julien.
