### ISSUE TITLE
Availibility of spring-cloud-dashboard in a public repository

### ISSUE THREAD

**Issue by Vad1mo** [VanRoy/spring-cloud-dashboard#4]
Are you planning to to release spring-cloud-dashboard in a public repository or to fork it back into spring-boot-admin so codecentric will take care of releasing and supporting your improvement.

**Comment by VanRoy** [comment]
Hi @Vad1mo, i'm waiting to "Spring Cloud Netflix" will be to be on GA for publish my artefact to maven central.
It will be soon, spring-cloud-netflix has currently in RC3.

The fork back to spring-boot-admin can be a good think, but the are some divergences that will be hard to merge : 

- One application has multiple Instances
- Circuit breaker
- All stream ( health, ... ) are proxified by dashboard instance ( not direclty call by browser ).

I don't now if codecentric will be interested by this features, i'll contact her to exchange over this point.

Thanks for you attention.
Julien.

**Comment by VanRoy** [comment]
spring-cloud-dashboard is now available on maven central.

<dependency>
    <groupId>com.github.vanroy</groupId>
    <artifactId>spring-cloud-dashboard</artifactId>
    <version>1.0.0.RELEASE</version>
</dependency>
