### ISSUE TITLE
Aggregated logging

### ISSUE THREAD

**Issue by ccit-spence** [VanRoy/spring-cloud-dashboard#5]
Have you considered some sort of a aggregated logging for the dashboard?  I have experimented a little with the ELK stack but the logstash agent is as large as my instances for RAM requirements.  

Something that utilizes the Spring Cloud Bus would be nice.

**Comment by VanRoy** [comment]
It's a good idea.
I had already thinked about an aggregated logging but i would like waiting for a standard solution from Spring Cloud.

If you have any idea about implementation, i'm open to contribution or idea.

Thanks a lot.
Julien.

**Comment by ccit-spence** [comment]
My concern is that since Cloud Foundry offers consolidated logging, the need only applies for those not on the Cloud Foundry platform.  We use AWS.

I will try to play around this week on something using Cloud Bus to consolidate the logs and then see how to integrate.  Elastic Search might be a need, rather than creating a search engine for the logs.

**Comment by VanRoy** [comment]
Hi @ccit-spence,

Do you have any news about you test of consolidated logging ?
I'm very interesting about that.

Julien.

**Comment by ccit-spence** [comment]
@VanRoy Right now I am centering our efforts around using Redis as an intermediary for an ELK stack.

In the Spring Boot app using the logback redisAppender for shipping of the logs.  So far initial testing is working pretty well.

**Comment by VanRoy** [comment]
Ok thanks.
I have do a another alternative on AWS based on logback SQS appender and logstash that push logs to ELK. It's work well toi.
