### ISSUE TITLE
Context-paths

### ISSUE THREAD

**Issue by ccit-spence** [VanRoy/spring-cloud-dashboard#6]
In its current state can the dashboard accept a different context-path?

Example: `http://hostname:port/dashboard/`

Then behind Zuul as: `http://diff-hostname/dashboard/`

Also, how would you set the actuator paths if they are loaded within a context-path of `hostname/admin/info`

**Comment by VanRoy** [comment]
Hi @ccit-spence ,

I have doing a little test with context-path and it's look like working.
Informed me if that not working for you.

For the actuator path, you need add this properties in your application.yml of the client application :

eureka.instance.metadata-map.managementPath: /admin

**Comment by VanRoy** [comment]
Can you confirm me if i can close this issue ?

**Comment by larry13767** [comment]
I tried it out (in the released version) and it does not seem to work.
eureka.instance.metadata-map.managementPath: /admin

The property is actually eureka.instance.metadataMap.managementPath

**Comment by VanRoy** [comment]
Hi @larry13767 ,

I think that in Spring Boot metadata-map and metadataMap are resolved identically ( cf "relaxed binding" section in http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html ).

Can you send me more informations / logs / code about your issue ?
