### ISSUE TITLE
How to show the logs and JMX section

### ISSUE THREAD

**Issue by EvilJinious1** [VanRoy/spring-cloud-dashboard#7]
I think you have done a great job.  I tried it out and it works quite well.

When I open up the logging table I see the filter by name input but there is nothing below that.  Is there something that is need in order to get it to show log parameters?

Same thing for JMX.  It is pretty much blank

**Comment by VanRoy** [comment]
Hi @larry13767 ,

The Log / JMX functionnalities require to you add the Jolokia dependency on your monitored services.
Jolokia expose JMX over HTTP ( more information here : http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-jmx.html )

For  gradle use : 
    runtime("org.jolokia:jolokia-core")

For maven use : 

<dependency>
    <groupId>org.jolokia</groupId>
    <artifactId>jolokia-core</artifactId>
 </dependency>

Tell me know if that don't fix the problem.
Julien.

**Comment by larry13767** [comment]
Thanks, I added the jolokia dependencies and the JMX section appeared.  I did some reading and found that when I added  <jmxConfigurator /> to my log back the logging section appeared.

Everythign is working now.  It is probably worthwhile to add a note on these two items so people don't pester you again.

And again, I want to thank you for this console, excellent job.

**Comment by VanRoy** [comment]
Thanks , can you have few minutes for create a PR to improve README.md ?

**Comment by pakizito** [comment]
Hi,
The console is just perfect! Good work.
I cannot see the Log part, why could this happen?

Thank you very much.
Rodrigo

**Comment by varghgeorge** [comment]
@VanRoy @EvilJinious1 
Similar to the other comments, Everything works great (even the JMX part). But not sure how to get Log section to display information. Can you please share details of it? I can create PR to add the details to README.md.

**Comment by VanRoy** [comment]
@pakizito, @varghgeorge , At this time, the logs section is not implemented. This is why you not see them :)
