### ISSUE TITLE
Circuit breakers disabled

### ISSUE THREAD

**Issue by Oreste-Luci** [VanRoy/spring-cloud-dashboard#8]
The dashboard looks great. Thanks.

How can I enable the Circuit breakers button on the Applications Page? Does it read the aggregated stream from Turbine?

**Comment by VanRoy** [comment]
Hi @Oreste-Luci ,

Turbine is required for activate circuit breaker on HomePage ( all instances are aggregated on same hystrix dashboard ).
On the detail page the you have access to another circuit breaker button that is only scoped to a instance. This one don't need turbine.

**Comment by Oreste-Luci** [comment]
Hi VanRoy,

Thanks for the answer.

I have Turbine running and can see all the aggregated streams in Hystrix Dashboard stand alone but in the Spring Cloud Dashboard (SCD) the Circuit Breakers buttons is disabled. Do I need to configure this in the SCD?

**Comment by VanRoy** [comment]
@Oreste-Luci , you can configure the turbine URL in SCD with this properties : spring.cloud.dashboard.turbine.url

The default value is : http://localhost:${server.port}/turbine.stream}
The clusterName in turbine must be equal to your applicationName.

You can see more information here : 

https://github.com/VanRoy/spring-cloud-dashboard/blob/8c64681857bce225bfcd968d14680b2d9eef9fbf/src/main/java/com/github/vanroy/cloud/dashboard/repository/eureka/EurekaRepository.java#L18

I hope this can help you.

**Comment by Oreste-Luci** [comment]
@VanRoy I've added `spring.cloud.dashboard.turbine.url: http://localhost:8989/turbine.stream` and it is working now.

Thank you!!

**Comment by VanRoy** [comment]
Ok great.

**Comment by brankoterzic** [comment]
Still get the disabled, after adding the suggested URL. When I paste http://localhost:8999/turbine.stream to my Hystrix Dashboard I get all the streams.

**Comment by VanRoy** [comment]
Hi @brankoterzic, thanks for your feedback.

So that I can help you, can you send me some information :

Which version of Dashboard do you use ?
It's the aggregated view that you can't view ( the button on home of dashboard ) ? 
Can you see hystrix dashboard when you go to one service with detail button ?

Thanks.
Julien.
