### ISSUE TITLE
How to connect to turbine

### ISSUE THREAD

**Issue by larry13767** [VanRoy/spring-cloud-dashboard#9]
As the title says, how would we connect the console to a turbine instance?

**Comment by popand** [comment]
Yeah I have been wondering about that too.. any insight would be much appreciated.

**Comment by Oreste-Luci** [comment]
I had the same problem and I fixed it by adding `spring.cloud.dashboard.turbine.url:` to the configuration. 

Have a look at this issue https://github.com/VanRoy/spring-cloud-dashboard/issues/8#issuecomment-106054868

**Comment by popand** [comment]
Awesome.. thanks a lot

**Comment by VanRoy** [comment]
@Oreste-Luci , @popand , is it fonctional for you ? Can i close this issue ?

**Comment by Oreste-Luci** [comment]
@VanRoy  yes, it is working for me. Thanks!
